Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Shared folders for provisioning and key/token sharing
  config.vm.synced_folder "./scripts", "/vagrant/scripts"
  config.vm.synced_folder "./shared", "/vagrant/shared", create: true

  # === Server VM: mannahriS ===
  config.vm.define "mannahriS" do |s|
    s.vm.hostname = "mannahriS"
    s.vm.network "private_network", ip: "192.168.56.110", nic_type: "82540EM"
    s.vm.provider "virtualbox" do |v|
      v.gui = true
      v.memory = 2048
      v.cpus = 2
    end
    s.vm.provision "shell", path: "./scripts/server.sh"
  end

  # === Worker VM: mannahriSW ===
  config.vm.define "mannahriSW" do |sw|
    sw.vm.hostname = "mannahriSW"
    sw.vm.network "private_network", ip: "192.168.56.111", nic_type: "82540EM"
    sw.vm.provider "virtualbox" do |v|
      v.gui = true
      v.memory = 1024
      v.cpus = 1
    end
    sw.vm.provision "shell", path: "./scripts/agent.sh"
  end
end
